export const intialFilterState = {
  housingTypes: {
    Apartment: false,
    Condo: false,
    Manufactured: false,
    Duplex: false,
    Townhouse: false,
    Loft: false,
    House: false,
    'Cottage/Cabin': false,
    Flat: false,
    'In-law': false,
    Land: false,
    'Assisted Living': false,
  },
  minPrice: '500',
  maxPrice: '1000',
  minSquareFeet: '500',
  maxSquareFeet: '1000',
  minBeds: '2',
  maxBeds: '3',
  minBaths: '2',
  maxBaths: '3',
};
